#!/usr/bin/env ruby
require 'sysdo'

include Sysdo::SourceLibrary

dsl = Sysdo::DSL.new
dsl.instance_eval(File.read(File.join(__dir__, 'user_config.rb')))
threads = dsl.event_sources.map do |src|
  t = Thread.new { src.listen }
  t.abort_on_exception = true
  t
end

puts "Press Enter to end..."
gets

threads.each(&:kill)
