#!/usr/bin/env ruby
require 'sysdo'
require 'fileutils'
require 'thwait'
require 'daemons'

include Sysdo::SourceLibrary

dsl = Sysdo::Dsl.new
Sysdo::Cli.user_scripts.each do |file|
  dsl.instance_eval(File.read(file))
end

Daemons.run_proc('sysdo') do
  threads = dsl.event_sources.map do |src|
    t = Thread.new { src.listen }
    t.abort_on_exception = true
    t
  end

  ThreadsWait.all_waits(*threads)
end
